# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceIniciar.ui'
#
# Created: Thu Apr 24 15:30:12 2014
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 330)
        Dialog.setMinimumSize(QtCore.QSize(530, 330))
        Dialog.setMaximumSize(QtCore.QSize(530, 330))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtGui.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(145, 177))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../.designer/logo_ufpa_sem_fundo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem = QtGui.QSpacerItem(13, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem)
        self.label_28 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setTextFormat(QtCore.Qt.RichText)
        self.label_28.setWordWrap(False)
        self.label_28.setOpenExternalLinks(True)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_14.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(Dialog)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_14.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(Dialog)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_14.addWidget(self.label_30)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.line_7 = QtGui.QFrame(Dialog)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_13.addWidget(self.line_7)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_31 = QtGui.QLabel(Dialog)
        self.label_31.setEnabled(True)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_15.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(Dialog)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_15.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(Dialog)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_15.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(Dialog)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_15.addWidget(self.label_34)
        self.label_35 = QtGui.QLabel(Dialog)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_15.addWidget(self.label_35)
        self.verticalLayout_13.addLayout(self.verticalLayout_15)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.line_8 = QtGui.QFrame(Dialog)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_7.addWidget(self.line_8)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 2, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.buttonTelecomunicacoes = QtGui.QPushButton(Dialog)
        self.buttonTelecomunicacoes.setCheckable(False)
        self.buttonTelecomunicacoes.setAutoDefault(True)
        self.buttonTelecomunicacoes.setDefault(False)
        self.buttonTelecomunicacoes.setFlat(False)
        self.buttonTelecomunicacoes.setObjectName("buttonTelecomunicacoes")
        self.verticalLayout_16.addWidget(self.buttonTelecomunicacoes)
        self.buttonGnuRadio = QtGui.QPushButton(Dialog)
        self.buttonGnuRadio.setAutoDefault(True)
        self.buttonGnuRadio.setDefault(False)
        self.buttonGnuRadio.setObjectName("buttonGnuRadio")
        self.verticalLayout_16.addWidget(self.buttonGnuRadio)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem2)
        self.buttonFechar = QtGui.QPushButton(Dialog)
        self.buttonFechar.setCheckable(False)
        self.buttonFechar.setAutoDefault(True)
        self.buttonFechar.setDefault(False)
        self.buttonFechar.setObjectName("buttonFechar")
        self.verticalLayout_16.addWidget(self.buttonFechar)
        self.gridLayout.addLayout(self.verticalLayout_16, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog", "SATEC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog", "Sistema de Aprendizagem", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Dialog", "de Telecomunicações", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Dialog", "Versão 1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog", "Copyright (c). 2013 - 2014", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog", "Universidade Federal do Pará", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Dialog", "Laboratório de Processamento de Sinais", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog", "Pará, Belém.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Quero aprender sobre:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonTelecomunicacoes.setText(QtGui.QApplication.translate("Dialog", "Telecomunicações", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonGnuRadio.setText(QtGui.QApplication.translate("Dialog", "GNU Radio", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFechar.setText(QtGui.QApplication.translate("Dialog", "Fechar", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

